export const dot = '.'
export const dash = '-'
export const space = ' '

export const table: [string, string][] = [
  ['イ', `${dot}${dash}`],
  ['ロ', `${dot}${dash}${dot}${dash}`],
  ['ハ', `${dash}${dot}${dot}${dot}`],
  ['ニ', `${dash}${dot}${dash}${dot}`],
  ['ホ', `${dash}${dot}${dot}`],
  ['ヘ', `${dot}`],
  ['ト', `${dot}${dot}${dash}${dot}${dot}`],
  ['チ', `${dot}${dot}${dash}${dot}`],
  ['リ', `${dash}${dash}${dot}`],
  ['ヌ', `${dot}${dot}${dot}${dot}`],
  ['ル', `${dash}${dot}${dash}${dash}${dot}`],
  ['ヲ', `${dot}${dash}${dash}${dash}`],
  ['ワ', `${dash}${dot}${dash}`],
  ['カ', `${dot}${dash}${dot}${dot}`],
  ['ヨ', `${dash}${dash}`],
  ['タ', `${dash}${dot}`],
  ['レ', `${dash}${dash}${dash}`],
  ['ソ', `${dash}${dash}${dash}${dot}`],
  ['ツ', `${dot}${dash}${dash}${dot}`],
  ['ネ', `${dash}${dash}${dot}${dash}`],
  ['ナ', `${dot}${dash}${dot}`],
  ['ラ', `${dot}${dot}${dot}`],
  ['ム', `${dash}`],
  ['ウ', `${dot}${dot}${dash}`],
  ['ヰ', `${dot}${dash}${dot}${dot}${dash}`],
  ['ノ', `${dot}${dot}${dash}${dash}`],
  ['オ', `${dot}${dash}${dot}${dot}${dot}`],
  ['ク', `${dot}${dot}${dot}${dash}`],
  ['ヤ', `${dot}${dash}${dash}`],
  ['マ', `${dash}${dot}${dot}${dash}`],
  ['ケ', `${dash}${dot}${dash}${dash}`],
  ['フ', `${dash}${dash}${dot}${dot}`],
  ['コ', `${dash}${dash}${dash}${dash}`],
  ['エ', `${dash}${dot}${dash}${dash}${dash}`],
  ['テ', `${dot}${dash}${dot}${dash}${dash}`],
  ['ア', `${dash}${dash}${dot}${dash}${dash}`],
  ['サ', `${dash}${dot}${dash}${dot}${dash}`],
  ['キ', `${dash}${dot}${dash}${dot}${dot}`],
  ['ユ', `${dash}${dot}${dot}${dash}${dash}`],
  ['メ', `${dash}${dot}${dot}${dot}${dash}`],
  ['ミ', `${dot}${dot}${dash}${dot}${dash}`],
  ['シ', `${dash}${dash}${dot}${dash}${dot}`],
  ['ヱ', `${dot}${dash}${dash}${dot}${dot}`],
  ['ヒ', `${dash}${dash}${dot}${dot}${dash}`],
  ['モ', `${dash}${dot}${dot}${dash}${dot}`],
  ['セ', `${dot}${dash}${dash}${dash}${dot}`],
  ['ス', `${dash}${dash}${dash}${dot}${dash}`],
  ['ン', `${dot}${dash}${dot}${dash}${dot}`],
  ['゛', `${dot}${dot}`],
  ['゜', `${dot}${dot}${dash}${dash}${dot}`],
]
